export const queries = {
    usuario : 'SELECT * FROM USUARIOS WHERE NOMBRECOMPLETO =@LOGIN AND  CLAVE =@PASS AND ESTADO =@STAT ',
    listadoEquipos : 'SELECT * FROM LISTADOEQUIPOS WHERE STATUS = @STAT AND PRESTADO =  @PRESTADO',
    prestamoEquipos : 'SELECT * FROM PRESTAMOSEQUIPOS WHERE DEVUELTO = @DEVUELTO ',
    equiposDevuletos : 'SELECT * FROM PRESTAMOSEQUIPOS WHERE DEVUELTO = @DEVUELTO ',
    cliente : 'SELECT  IDCLIENTE,NOMBRE1,APELLIDO1,DOCUMENTO,EMAIL,TELEFONO2 FROM CLIENTE',
    documentosGarantias : 'SELECT * FROM DOCUMENTOGARANTIAS ORDER BY DOCUMENTO ASC',
    asuntoEntrega : 'select * from observacionesprestamos',    
    crearPrestamo : `INSERT INTO PRESTAMOSEQUIPOS(IDCLIENTE,DOCUMENTO,NOMBRECOMPLETO,IDEQUIPO,EQUIPO,SERIAL,IDDOCUMENTOGARANTIA,DOCUMENTOGARANTIA,IDOBSERVACIONENTREGA,OBSERVACIONENTREGA,OBSERVACIONESDENETREGA,FECHAENTREGA,DEVUELTO,USUARIOCREA,FECHACREACION,USUARIOENTREGA,PRESTADO)
    VALUES (@IDCLIENTE,@DOCUMENTO,@NOMBRECOMPLETO,@IDEQUIPO,@EQUIPO,@SERIAL,@IDDOCUMENTOGARANTIA,@DOCUMENTOGARANTIA,@IDOBSERVACIONENTREGA,@OBSERVACIONENTREGA,@OBSERVACIONESDEENTREGA,@FECHAENTREGA,@DEVUELTO,@USUARIOCREA,GETDATE(),@USUARIOENTREGA,@PRESTADO)`,
    actualizarEquipo :'UPDATE LISTADOEQUIPOS SET PRESTADO = @PRESTADO WHERE IDLISTADOEQUIPO = @IDLISTADOEQUIPO',
    equipoSeleccionado : 'SELECT * FROM PRESTAMOSEQUIPOS WHERE IDPRESTAMOEQUIPO = @ID',
    actualizarPrestamo : `UPDATE [dbo].[PRESTAMOSEQUIPOS]
    SET [IDCLIENTE] = @IDCLIENTE
       ,[DOCUMENTO] = @DOCUMENTO
       ,[NOMBRECOMPLETO] = @NOMBRECOMPLETO
       ,[IDEQUIPO] = @IDEQUIPO
       ,[EQUIPO] = @EQUIPO
       ,[SERIAL] = @SERIAL
       ,[IDDOCUMENTOGARANTIA] = @IDDOCUMENTOGARANTIA
       ,[DOCUMENTOGARANTIA] = @DOCUMENTOGARANTIA
       ,[IDOBSERVACIONENTREGA] = @IDOBSERVACIONENTREGA
       ,[OBSERVACIONENTREGA] = @OBSERVACIONENTREGA
       ,[OBSERVACIONESDENETREGA] = @OBSERVACIONESDENETREGA
       ,[USUARIOMODIFICA] = @USUARIOMODIFICA
       ,[FECHAMODIFICA] = GETDATE()
       WHERE IDPRESTAMOEQUIPO = @ID
  `,
  actualizarDevolucion  : 'UPDATE [dbo].[PRESTAMOSEQUIPOS] SET IDOBSERVACIONRECIBIDO = @IDOBSERVACIONRECIBIDO, OBSERVACIONRECIBIDO = @OBSERVACIONRECIBIDO, OBSERVACIONESDERECIBIDO = @OBSERVACIONESDERECIBIDO,DEVUELTO = @DEVUELTO, USUARIORECIBE=@USUARIORECIBE,PRESTADO = @PRESTADO,FECHADEVOLUCION = GETDATE() WHERE IDPRESTAMOEQUIPO = @ID',
  tipoDocumento : 'SELECT * FROM REFERENCIAS WHERE IDTIPOREFERENCIA = 3',
  genero: 'SELECT * FROM REFERENCIAS WHERE IDTIPOREFERENCIA = 1',
  ciudad : 'SELECT * FROM REFERENCIAS WHERE IDTIPOREFERENCIA = 2',
  crearCliente : 'INSERT INTO [dbo].[CLIENTE] '+
    '([NOMBRE1],[NOMBRE2],[APELLIDO1],[APELLIDO2],[IDTIPODOCUMENTO],[DOCUMENTO],[IDSEXO],[EMAIL],[DIRECCIONRESIDENCIA],[IDCIUDADRESIDENCIA],[USUARIOCREA],[FECHACREACION],[FECHANACIMIENTO],[TELEFONO2],[HACIENDAFONTANAR],[FONTANARENTRENA],[BIKELOVERS],[CARLOVERS],[MOMS],[SEPARADOS],[MUJEREMPRENDEDORA],[ENTRETENIMIENTONINOS])'+
    'VALUES'+
    '(@NOMBRE1,@NOMBRE2,@APELLIDO1,@APELLIDO2,@IDTIPODOCUMENTO,@DOCUMENTO,@IDSEXO,@EMAIL,@DIRECCIONRESIDENCIA,@IDCIUDADRESIDENCIA,@USUARIOCREA,GETDATE(),@FECHANACIMIENTO,@TELEFONO2,@HACIENDAFONTANAR,@FONTANARENTRENA,@BIKELOVERS,@CARLOVERS,@MOMS,@SEPARADOS,@MUJEREMPRENDEDORA,@ENTRETENIMIENTONINOS)'
}